version: "3"

networks:
  laravel:

volumes:
  data:

services:
  db:
    image: mysql:5.6
    container_name: sw-mysql
    ports:
      - "3307:3306"
    volumes:
      - data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=satc
    networks:
      - laravel
  nginx:
    image: nginx:stable-alpine
    container_name: sw-nginx
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - .:/var/www/html:cached
      - ./dockerfiles/config/nginx.default.conf:/etc/nginx/conf.d/default.conf:cached
    depends_on:
      - php
      - db
    networks:
      - laravel
  php:
    image: satc/php:7.3
    build:
      context: ./dockerfiles
      dockerfile: php7.3.dockerfile
    container_name: sw-php
    depends_on:
      - db
    volumes:
      - .:/var/www/html:cached
      - ./dockerfiles/config/php.ini:/usr/local/etc/php/php.ini:cached
    ports:
      - "9000:9000"
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sw-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=sw-mysql
    depends_on:
      - db
    networks:
      - laravel
